// Generated by the storefront image pipeline. Lists the images present in public/storefront.
export const CATEGORY_IMAGE_SLUGS = new Set<string>([]);
export const CARD_IMAGE_SLUGS = new Set<string>([]);
export const BANNER_IMAGES = new Set<string>([]);
