import { EmailTemplateResult } from '../../types.js';
import { renderBrandedEmail } from './layout.js';
import { portalLinks } from './portal-links.js';

export function adminAlertTemplate(data: { title: string, message: string }): EmailTemplateResult {
    return {
        subject: `[KTMONA Admin Alert] ${data.title}`,
        html: renderBrandedEmail({
            preheader: `Admin alert: ${data.title}`,
            eyebrow: 'Admin Monitoring',
            title: 'Action Required: Admin Alert',
            message: [
                'An operational alert has been generated by the KTMONA platform.',
                data.message,
            ],
            details: [{ label: 'Alert', value: data.title }],
            ctaLabel: 'Open Admin Dashboard',
            ctaUrl: portalLinks.adminDashboard,
            accentText: 'Please review this alert promptly and take necessary action.',
        }),
    };
}